create extension if not exists pgcrypto;

create sequence if not exists public.downtime_call_seq start 1;

create table if not exists public.calls (
  id uuid primary key default gen_random_uuid(),
  call_number text unique not null default (
    'D' || to_char(now(), 'YYMMDD') || '-' ||
    lpad(nextval('public.downtime_call_seq')::text, 4, '0')
  ),
  address text not null,
  fire_response text,
  jcso_beat text,
  law boolean not null default false,
  fire boolean not null default false,
  ems boolean not null default false,
  law_call_type text,
  fire_call_type text,
  ems_call_type text,
  caller_name text,
  callback_number text,
  status text not null default 'PENDING'
    check (status in ('PENDING','DISPATCHED','ACTIVE','HOLDING','CLOSED')),
  created_by uuid references auth.users(id),
  created_by_name text not null,
  created_by_role text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz,
  closed_by_name text
);

create table if not exists public.narratives (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.calls(id) on delete cascade,
  body text not null,
  author_id uuid references auth.users(id),
  author_name text not null,
  author_role text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_calls_status_created
  on public.calls(status, created_at desc);

create index if not exists idx_narratives_call_created
  on public.narratives(call_id, created_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_calls_updated_at on public.calls;
create trigger trg_calls_updated_at
before update on public.calls
for each row execute function public.set_updated_at();

alter table public.calls enable row level security;
alter table public.narratives enable row level security;

drop policy if exists "calls_authenticated_select" on public.calls;
create policy "calls_authenticated_select"
on public.calls for select to authenticated using (true);

drop policy if exists "calls_authenticated_insert" on public.calls;
create policy "calls_authenticated_insert"
on public.calls for insert to authenticated
with check (auth.uid() = created_by);

drop policy if exists "calls_authenticated_update" on public.calls;
create policy "calls_authenticated_update"
on public.calls for update to authenticated
using (true) with check (true);

drop policy if exists "narratives_authenticated_select" on public.narratives;
create policy "narratives_authenticated_select"
on public.narratives for select to authenticated using (true);

drop policy if exists "narratives_authenticated_insert" on public.narratives;
create policy "narratives_authenticated_insert"
on public.narratives for insert to authenticated
with check (auth.uid() = author_id);

grant select, insert, update on public.calls to authenticated;
grant select, insert on public.narratives to authenticated;
grant usage, select on sequence public.downtime_call_seq to authenticated;

alter publication supabase_realtime add table public.calls;
alter publication supabase_realtime add table public.narratives;
